### ISSUE TITLE
Добавить в iTunes

### ISSUE THREAD

**Issue by AlekSi** [GolangShow/golangshow.com#5]

**Comment by php-coder** [comment]
Да, это было бы очень удобно.

**Comment by AlekSi** [comment]
@php-coder О, привет, старый знакомый по `cppcheck`. :)

**Comment by php-coder** [comment]
@AlekSi Привет :) Да, давно это было)

Я пока от вашего подкаста прослушал первый выпуск, потому что в основном слушаю в дороге и, как раз, через iTunes, поэтому жду исправления этой задачи, чтобы начать слушать.

Вероятно, можно спросить у ребят из DevZen-а, если возникнут какие-то трудности, т.к. они на iTunes есть.

**Comment by miolini** [comment]
@php-coder 
Дорогой слушатель, у вас есть возможность в мобильным Safari зайти на сайт http://golangshow.com и нажать кнопку "Подписаться". Наш подкаст появится в вашем девайсе.

**Comment by php-coder** [comment]
@miolini Спасибо, действительно помогло! Надеюсь, такая подписка нормально синхронизируется с десктопом потом.

До этого пытался подписываться через сам iTunes с Мака.

**Comment by miolini** [comment]
С iTunes есть проблемы. Решаем через их службу поддержки.

**Comment by AlekSi** [comment]
https://itunes.apple.com/ru/podcast/podkast-golangshow/id1031101295
